Exception Cause: 29  [StoreProhibited: A store referenced a page mapped with an attribute that does not permit stores]

0x40202f95: Adafruit_GFX::Adafruit_GFX(short, short) at C:\Users\EV7\Documents\Arduino\libraries\Adafruit_GFX/Adafruit_GFX.cpp:2502
0x401009fc: malloc at C:\Users\EV7\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\umm_malloc/umm_info.c:178
0x40205624: operator new(unsigned int) at ??:?
0x402043a8: Adafruit_ST77xx::Adafruit_ST77xx(unsigned short, unsigned short, signed char, signed char, signed char) at C:\Users\EV7\Documents\Arduino\libraries\Adafruit_ST7735/Adafruit_ST77xx.cpp:65
0x402041a0: Adafruit_ST7735::Adafruit_ST7735(signed char, signed char, signed char) at C:\Users\EV7\Documents\Arduino\libraries\Adafruit_ST7735/Adafruit_ST7735.cpp:211
0x40205624: operator new(unsigned int) at ??:?
0x402025a2: Painter::Painter(int, int, int) at s:\product\programming\in_progress\real_tetris\ESPOutput\sketch/Painter.cpp:251
0x40201972: __gnu_cxx::new_allocator<std::_Sp_counted_deleter<Painter*, std::__shared_ptr<Painter, (__gnu_cxx::_Lock_policy)0>::_Deleter<std::allocator<Painter> >, std::allocator<Painter>, (__gnu_cxx::_Lock_policy)0> >::allocate(unsigned int, void const*) at c:\users\ev7\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506\xtensa-lx106-elf\include\c++\5.2.0\bits/shared_ptr_base.h:127
 (inlined by) std::allocator_traits<std::allocator<std::_Sp_counted_deleter<Painter*, std::__shared_ptr<Painter, (__gnu_cxx::_Lock_policy)0>::_Deleter<std::allocator<Painter> >, std::allocator<Painter>, (__gnu_cxx::_Lock_policy)0> > >::allocate(std::allocator<std::_Sp_counted_deleter<Painter*, std::__shared_ptr<Painter, (__gnu_cxx::_Lock_policy)0>::_Deleter<std::allocator<Painter> >, std::allocator<Painter>, (__gnu_cxx::_Lock_policy)0> >&, unsigned int) at c:\users\ev7\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506\xtensa-lx106-elf\include\c++\5.2.0\bits/alloc_traits.h:360
 (inlined by) std::__allocated_ptr<std::allocator<std::_Sp_counted_deleter<Painter*, std::__shared_ptr<Painter, (__gnu_cxx::_Lock_policy)0>::_Deleter<std::allocator<Painter> >, std::allocator<Painter>, (__gnu_cxx::_Lock_policy)0> > > std::__allocate_guarded<std::allocator<std::_Sp_counted_deleter<Painter*, std::__shared_ptr<Painter, (__gnu_cxx::_Lock_policy)0>::_Deleter<std::allocator<Painter> >, std::allocator<Painter>, (__gnu_cxx::_Lock_policy)0> > >(std::allocator<std::_Sp_counted_deleter<Painter*, std::__shared_ptr<Painter, (__gnu_cxx::_Lock_policy)0>::_Deleter<std::allocator<Painter> >, std::allocator<Painter>, (__gnu_cxx::_Lock_policy)0> >&) at c:\users\ev7\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506\xtensa-lx106-elf\include\c++\5.2.0\bits/allocated_ptr.h:102
 (inlined by) std::__shared_count<(__gnu_cxx::_Lock_policy)0>::__shared_count<Painter*, std::__shared_ptr<Painter, (__gnu_cxx::_Lock_policy)0>::_Deleter<std::allocator<Painter> >, std::allocator<Painter> >(Painter*, std::__shared_ptr<Painter, (__gnu_cxx::_Lock_policy)0>::_Deleter<std::allocator<Painter> >, std::allocator<Painter>) at c:\users\ev7\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506\xtensa-lx106-elf\include\c++\5.2.0\bits/shared_ptr_base.h:595
 (inlined by) std::__shared_ptr<Painter, (__gnu_cxx::_Lock_policy)0>::__shared_ptr<std::allocator<Painter>, int&, int&, int&>(std::_Sp_make_shared_tag, std::allocator<Painter> const&, int&, int&, int&) at c:\users\ev7\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506\xtensa-lx106-elf\include\c++\5.2.0\bits/shared_ptr_base.h:1132
 (inlined by) std::shared_ptr<Painter>::shared_ptr<std::allocator<Painter>, int&, int&, int&>(std::_Sp_make_shared_tag, std::allocator<Painter> const&, int&, int&, int&) at c:\users\ev7\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506\xtensa-lx106-elf\include\c++\5.2.0\bits/shared_ptr.h:319
 (inlined by) std::shared_ptr<Painter> std::allocate_shared<Painter, std::allocator<Painter>, int&, int&, int&>(std::allocator<Painter> const&, int&, int&, int&) at c:\users\ev7\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506\xtensa-lx106-elf\include\c++\5.2.0\bits/shared_ptr.h:614
 (inlined by) std::shared_ptr<Painter> std::make_shared<Painter, int&, int&, int&>(int&, int&, int&) at c:\users\ev7\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506\xtensa-lx106-elf\include\c++\5.2.0\bits/shared_ptr.h:630
 (inlined by) Display::Display(Size, int, int, int) at s:\product\programming\in_progress\real_tetris\ESPOutput\sketch/Display.cpp:18
0x40205600: operator new[](unsigned int) at C:\Users\EV7\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266/abi.cpp:49
0x40201ca2: __gnu_cxx::new_allocator<std::_Sp_counted_deleter<TextView*, std::__shared_ptr<TextView, (__gnu_cxx::_Lock_policy)0>::_Deleter<std::allocator<TextView> >, std::allocator<TextView>, (__gnu_cxx::_Lock_policy)0> >::allocate(unsigned int, void const*) at c:\users\ev7\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506\xtensa-lx106-elf\include\c++\5.2.0\bits/shared_ptr_base.h:466
 (inlined by) std::allocator_traits<std::allocator<std::_Sp_counted_deleter<Display*, std::__shared_ptr<Display, (__gnu_cxx::_Lock_policy)0>::_Deleter<std::allocator<Display> >, std::allocator<Display>, (__gnu_cxx::_Lock_policy)0> > >::allocate(std::allocator<std::_Sp_counted_deleter<Display*, std::__shared_ptr<Display, (__gnu_cxx::_Lock_policy)0>::_Deleter<std::allocator<Display> >, std::allocator<Display>, (__gnu_cxx::_Lock_policy)0> >&, unsigned int) at c:\users\ev7\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506\xtensa-lx106-elf\include\c++\5.2.0\bits/alloc_traits.h:360
 (inlined by) std::__allocated_ptr<std::allocator<std::_Sp_counted_deleter<Display*, std::__shared_ptr<Display, (__gnu_cxx::_Lock_policy)0>::_Deleter<std::allocator<Display> >, std::allocator<Display>, (__gnu_cxx::_Lock_policy)0> > > std::__allocate_guarded<std::allocator<std::_Sp_counted_deleter<Display*, std::__shared_ptr<Display, (__gnu_cxx::_Lock_policy)0>::_Deleter<std::allocator<Display> >, std::allocator<Display>, (__gnu_cxx::_Lock_policy)0> > >(std::allocator<std::_Sp_counted_deleter<Display*, std::__shared_ptr<Display, (__gnu_cxx::_Lock_policy)0>::_Deleter<std::allocator<Display> >, std::allocator<Display>, (__gnu_cxx::_Lock_policy)0> >&) at c:\users\ev7\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506\xtensa-lx106-elf\include\c++\5.2.0\bits/allocated_ptr.h:102
 (inlined by) std::__shared_count<(__gnu_cxx::_Lock_policy)0>::__shared_count<Display*, std::__shared_ptr<Display, (__gnu_cxx::_Lock_policy)0>::_Deleter<std::allocator<Display> >, std::allocator<Display> >(Display*, std::__shared_ptr<Display, (__gnu_cxx::_Lock_policy)0>::_Deleter<std::allocator<Display> >, std::allocator<Display>) at c:\users\ev7\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506\xtensa-lx106-elf\include\c++\5.2.0\bits/shared_ptr_base.h:595
 (inlined by) std::__shared_ptr<Display, (__gnu_cxx::_Lock_policy)0>::__shared_ptr<std::allocator<Display>, Size, int, int, int>(std::_Sp_make_shared_tag, std::allocator<Display> const&, Size&&, int&&, int&&, int&&) at c:\users\ev7\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506\xtensa-lx106-elf\include\c++\5.2.0\bits/shared_ptr_base.h:1132
 (inlined by) std::shared_ptr<Display>::shared_ptr<std::allocator<Display>, Size, int, int, int>(std::_Sp_make_shared_tag, std::allocator<Display> const&, Size&&, int&&, int&&, int&&) at c:\users\ev7\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506\xtensa-lx106-elf\include\c++\5.2.0\bits/shared_ptr.h:319
 (inlined by) std::shared_ptr<Display> std::allocate_shared<Display, std::allocator<Display>, Size, int, int, int>(std::allocator<Display> const&, Size&&, int&&, int&&, int&&) at c:\users\ev7\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506\xtensa-lx106-elf\include\c++\5.2.0\bits/shared_ptr.h:614
 (inlined by) std::shared_ptr<Display> std::make_shared<Display, Size, int, int, int>(Size&&, int&&, int&&, int&&) at c:\users\ev7\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506\xtensa-lx106-elf\include\c++\5.2.0\bits/shared_ptr.h:630
 (inlined by) Game::initializeDisplay() at s:\product\programming\in_progress\real_tetris\ESPOutput\sketch/Game.cpp:190
0x40201c38: Game::initializeConfig() at c:\users\ev7\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506\xtensa-lx106-elf\include\c++\5.2.0\bits/shared_ptr_base.h:466
0x40202091: Game::initialize() at c:\users\ev7\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506\xtensa-lx106-elf\include\c++\5.2.0\bits/shared_ptr_base.h:466
0x40204d60: HardwareSerial::begin(unsigned long, SerialConfig, SerialMode, unsigned char, bool) at C:\Users\EV7\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266/HardwareSerial.cpp:131
0x401009fc: malloc at C:\Users\EV7\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266\umm_malloc/umm_info.c:178
0x40205600: operator new[](unsigned int) at C:\Users\EV7\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266/abi.cpp:49
0x402021a9: Game::start() at c:\users\ev7\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506\xtensa-lx106-elf\include\c++\5.2.0\bits/shared_ptr_base.h:466
0x402010dc: std::__shared_ptr<Game, (__gnu_cxx::_Lock_policy)0>::~__shared_ptr() at s:\product\programming\in_progress\real_tetris\Tetrisimo_Esp\source/Background.cpp:20
 (inlined by) std::shared_ptr<Game>::~shared_ptr() at c:\users\ev7\appdata\local\arduino15\packages\esp8266\tools\xtensa-lx106-elf-gcc\2.5.0-4-b40a506\xtensa-lx106-elf\include\c++\5.2.0\bits/shared_ptr.h:93
 (inlined by) setup at s:\product\programming\in_progress\real_tetris\Tetrisimo_Esp\source/Tetrisimo_Esp.ino:6
0x40205864: loop_wrapper() at C:\Users\EV7\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266/core_esp8266_main.cpp:194
0x40100c79: cont_wrapper at C:\Users\EV7\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\cores\esp8266/cont.S:81
0x40205624: operator new(unsigned int) at ??:?
0x4010f000: ?? ??:0
